from fpdf import FPDF
from datetime import datetime


class CropReport(FPDF):
    def header(self):
        self.set_fill_color(22, 163, 74)
        self.rect(0, 0, 210, 18, "F")
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(255, 255, 255)
        self.set_xy(10, 4)
        self.cell(0, 10, "CropGuard AI  -  Disease Analysis Report", align="L")
        self.set_text_color(0, 0, 0)
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(
            0, 10,
            f"Generated on {datetime.now().strftime('%d %b %Y %H:%M')}  |  Page {self.page_no()}",
            align="C"
        )

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(30, 41, 59)
        self.cell(0, 8, title, ln=True)
        self.set_draw_color(99, 102, 241)
        self.set_line_width(0.5)
        self.line(self.l_margin, self.get_y(), 200, self.get_y())
        self.ln(4)

    def key_value(self, key: str, value: str,
                  key_rgb=(71, 85, 105), val_rgb=(15, 23, 42)):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*key_rgb)
        self.cell(55, 7, key, border=0)
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*val_rgb)
        self.cell(0, 7, value, ln=True)


def generate_report_pdf(
    username: str,
    disease_name: str,
    confidence: float,
    severity: str,
    description: str,
    treatments: list,
) -> bytes:
    """Generate a styled PDF report and return as bytes."""

    pdf = CropReport()
    pdf.set_margins(left=15, top=10, right=15)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Scan Summary ──
    pdf.section_title("Scan Summary")
    pdf.key_value("Analysed By:", username)
    pdf.key_value("Date & Time:", datetime.now().strftime("%d %B %Y, %I:%M %p"))
    pdf.ln(4)

    # ── Detection Results ──
    pdf.section_title("Detection Results")

    # Disease name highlighted box
    pdf.set_fill_color(238, 242, 255)
    pdf.set_draw_color(199, 210, 254)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(67, 56, 202)
    pdf.cell(0, 12, f"  Detected Disease:  {disease_name}", border=1, ln=True, fill=True)
    pdf.ln(3)

    # Confidence row
    pdf.key_value("Confidence Score:", f"{confidence:.1f}%", val_rgb=(99, 102, 241))

    # Severity row with colour
    sev_colors = {
        "None":     (16, 185, 129),
        "Low":      (210, 160, 8),
        "Moderate": (220, 100, 22),
        "High":     (200, 50, 50),
    }
    sv_rgb = sev_colors.get(severity, (100, 100, 100))
    pdf.key_value("Severity Level:", severity, val_rgb=sv_rgb)
    pdf.ln(4)

    # ── About This Disease ──
    if description:
        pdf.section_title("About This Disease")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(51, 65, 85)
        # Use effective page width for multi_cell
        pdf.multi_cell(pdf.epw, 6, description)
        pdf.ln(4)

    # ── Treatment Recommendations ──
    if treatments:
        pdf.section_title("Treatment Recommendations")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(51, 65, 85)
        for i, t in enumerate(treatments, 1):
            # Use a full-width multi_cell with numbered prefix in the text
            pdf.multi_cell(pdf.epw, 7, f"{i}. {t}")
            pdf.ln(1)
        pdf.ln(2)

    # ── Disclaimer ──
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(148, 163, 184)
    pdf.multi_cell(
        pdf.epw, 5,
        "Disclaimer: This report is generated by an AI model and is intended for "
        "informational purposes only. Please consult a certified agronomist for "
        "professional advice."
    )

    return bytes(pdf.output())
